_wandb:
    value:
        cli_version: 0.24.0
        e:
            v3g6bfsszlok77hgk6m7vcg6vtppp7uo:
                args:
                    - --enable_sparse_masking
                    - --sparsity_rate
                    - "0.95"
                    - --sparsity_compression
                    - CSR
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "943183376384"
                        used: "841325469696"
                email: kyrose0.2@gmail.com
                executable: /home/timevisao/dieRoche/.dieRoche/bin/python
                git:
                    commit: 6633d0357aac5e5cd1a5a7ba60c97b045c4477e4
                    remote: git@github.com:DieRoche/fedavg_copy.git
                host: B560M-DS3H
                memory:
                    total: "50372743168"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/timevisao/dieRoche/fedavg_copy/main.py
                python: CPython 3.10.12
                root: /home/timevisao/dieRoche/fedavg_copy
                startedAt: "2026-01-29T21:28:23.975318Z"
                writerId: v3g6bfsszlok77hgk6m7vcg6vtppp7uo
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
                - 61
            "4": 3.10.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 128
client_fraction:
    value: 1
dataset:
    value: cifar10
device:
    value: cuda
dirichlet:
    value: 0.5
enable_sparse_masking:
    value: true
lambd:
    value: 0
lr:
    value: 0.01
method:
    value: fedavg
model:
    value: resnet
n_client:
    value: 10
n_client_epoch:
    value: 5
n_epoch:
    value: 100
ours_n_sample:
    value: 1
s:
    value: 10
seed:
    value: 5
sparsity_compression:
    value: CSR
sparsity_min_density:
    value: 0.05
sparsity_rate:
    value: 0.95
topk:
    value: 0.01
train_frac:
    value: 0.8
wandb_enabled:
    value: true
